### ISSUE TITLE
ansible against ubuntu 18.10

### ISSUE THREAD

**Issue by ruebenramirez** [ruebenramirez/blog#417]
ran into a problem today running ansible against an ubuntu 18.10 host.  Python 3 is installed by default, but ansible still depends on Python 2.

This snippet can be added to the top of your playbook to ensure python 2 is available on your host so that ansible will run correctly against it:  

```
- hosts: all
  gather_facts: False
  
  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
```

source: https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f
